import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  releaseNotesSidebar: [
    {
      type: 'doc',
      id: 'index', 
    },
    {
      type: 'category',
      label: 'n8n Oficial',
      link: {
        type: 'doc',
        id: 'n8n-oficial/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'n8n-oficial/n8n',
        },
      ],
    },
    {
      type: 'category',
      label: 'Nossa Documentação',
      link: {
        type: 'generated-index',
        title: 'Releases da Documentação',
        description: 'Atualizações e melhorias feitas em nosso projeto de documentação.',
        slug: '/nossa-doc',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'nossa-doc',
        },
      ],
    },
  ],
};

export default sidebars; 